### ISSUE TITLE
import io.flutter.plugin.common.PluginRegistry.Registrar removed in Flutter 3.29.0 and it breaks the project build.

### ISSUE THREAD

**Issue by ritikjainx** [CleverTap/clevertap-flutter#295]
Fluttter version -  3.29.0 
Dart 3.7.0 
clevertap_plugin: ^3.0.0

I need to try upgrading flutter to 3.29.0 because:
- It improvise the impeller engine support for android for low end devices selecting the rendering engine.
- It contains stability and improvement updates for impeller

I think people would try to update to new version to make their apps more performant and hence Clevertap plugin also needs an update.

This issue occurs because the Registrar API has been removed in recent versions of Flutter, and the library needs to be updated to use the FlutterPlugin API instead.

<details>
<summary>Logs</summary>
<br>

```
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapPlugin.java:66: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapPlugin.java:110: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class CleverTapPlugin
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapPlugin.java:1883: error: cannot find symbol
    private MethodChannel getMethodChannel(String channelName, BinaryMessenger messenger, Registrar registrar) {
                                                                                          ^
  symbol:   class Registrar
  location: class CleverTapPlugin
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapPlugin.java:1893: error: cannot find symbol
    private void setupPlugin(Context context, BinaryMessenger messenger, Registrar registrar) {
                                                                         ^
  symbol:   class Registrar
  location: class CleverTapPlugin
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapApplication.java:11: error: package io.flutter.app does not exist
import io.flutter.app.FlutterApplication;
                     ^
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapApplication.java:13: error: cannot find symbol
public class CleverTapApplication extends FlutterApplication implements CTPushNotificationListener {
                                          ^
  symbol: class FlutterApplication
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapApplication.java:17: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapApplication.java:19: error: cannot find symbol
        super.onCreate();
        ^
  symbol:   variable super
  location: class CleverTapApplication
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapApplication.java:21: error: incompatible types: CleverTapApplication cannot be converted to Context
        CleverTapAPI cleverTapAPI = CleverTapAPI.getDefaultInstance(this);
                                                                    ^
/Users/ritikjain/.pub-cache/hosted/pub.dev/clevertap_plugin-2.5.0/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapApplication.java:31: error: incompatible types: CleverTapApplication cannot be converted to Context
        CleverTapBackgroundIsolateRunner.startBackgroundIsolate(this, payload);
                                                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
10 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clevertap_plugin:compileProfileJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
</details>

**Comment by msaqib-tradeling** [comment]
@Anush-Shand As suggested by you, I am using the following:
`  clevertap_plugin:
    git:
      url: https://github.com/CleverTap/clevertap-flutter.git
      ref: task/SDK-4406/support_corev7.1.2`

build is failing with this error:

`clevertap-flutter-397c66ea0e1c0efe767f336d4bc213be83b404cb/android/src/main/java/com/clevertap/clevertap_plugin/DartToNativePlatformCommunicator.kt:1152:79 Unresolved reference: CleverTapListenerProxy`

**Comment by Anush-Shand** [comment]
@msaqib-tradeling That is weird
As I checked CleverTapListenerProxy is present as a class https://github.com/CleverTap/clevertap-flutter/blob/task/SDK-4406/support_corev7.1.2/android/src/main/java/com/clevertap/clevertap_plugin/CleverTapListenerProxy.kt

Can you check your directories if this class is present when you include the flutter plugin?

**Comment by msaqib-tradeling** [comment]
@Anush-Shand doing flutter clean and regenerating pubspec.lock fixed my issue. I am now able to build with flutter version 3.29.0 for `task/SDK-4406/support_corev7.1.2` branch

**Comment by Anush-Shand** [comment]
This has been fixed in [v3.1.0](https://github.com/CleverTap/clevertap-flutter/releases/tag/3.1.0)
